---
- name: "Download and unarchive Packer"
  unarchive:
    src: "https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip"
    dest: "/usr/local/bin"
    remote_src: true
    creates: "/usr/local/bin/packer"
    mode: 0755

- name: "Download and unarchive Vagrant"
  unarchive:
    src: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_linux_amd64.zip"
    dest: "/usr/local/bin"
    remote_src: true
    creates: "/usr/local/bin/vagrant"
    mode: 0755

- name: "Download and unarchive Terraform"
  unarchive:
    src: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: "/usr/local/bin"
    remote_src: true
    creates: "/usr/local/bin/terraform"
    mode: 0755
