---
- name: "Check that the .oh-my-zsh exists"
  stat:
    path: "{{ user_data_dir }}/.oh-my-zsh"
  register: check_result

- name: "Git clone Oh-My-Zsh for users"
  command: "git clone -c core.autocrlf=input --depth=1 https://github.com/robbyrussell/oh-my-zsh.git {{ user_data_dir }}/.oh-my-zsh"
  when: not check_result.stat.exists

- name: "Check that the powerlevel10k exists"
  stat:
    path: "{{ user_data_dir }}/.oh-my-zsh/custom/themes/powerlevel10k"
  register: check_result_powerlevel10k

- name: "Git clone powerlevel10k for users"
  command: "git clone --depth=1 https://github.com/romkatv/powerlevel10k.git {{ user_data_dir }}/.oh-my-zsh/custom/themes/powerlevel10k"
  when: not check_result_powerlevel10k.stat.exists

#- name: clone oh-my-zsh for users
#  become: yes
#  become_user: '{{ item.username }}'
#  git:
#    repo: 'https://github.com/robbyrussell/oh-my-zsh.git'
#    version: master
#    dest: '~/.oh-my-zsh'
#  with_items: '{{ users }}'
#  when: users is defined
#
#- name: clone powerlevel10k for users
#  become: yes
#  become_user: '{{ item.username }}'
#  git:
#    repo: 'https://github.com/romkatv/powerlevel10k.git'
#    version: master
#    dest: '~/.oh-my-zsh/custom/themes/powerlevel10k'
#  with_items: '{{ users }}'
#  when: users is defined

- name: "Set permissions of Oh-My-Zsh for users"
  file:
    path: "{{ user_data_dir }}/.oh-my-zsh"
    mode: "go-w"
    recurse: yes

- name: "Set default shell for users"
  user:
    name: "{{ user }}"
    shell: "/bin/zsh"

- name: "Write .zshrc for users"
  template:
    src: zshrc.j2
    dest: "{{ user_data_dir }}/.zshrc"
    backup: yes
    mode: 0775

- name: "Write .p10k.zsh for users"
  copy:
    src: .p10k.zsh
    dest: "{{ user_data_dir }}/.p10k.zsh"
    backup: yes
    mode: 0755