---
- name: "Add TeamViewer apt-key"
  apt_key:
    url: "http://download.teamviewer.com/download/linux/signature/TeamViewer2017.asc"
    id: "8CAE012EBFAC38B17A937CD8C5E224500C1289C0"
    state: present

- name: "Add TeamViewer apt-repository"
  apt_repository:
    repo: "deb http://linux.teamviewer.com/deb stable main"
    filename: "teamviewer"
    state: present
    mode: 0644

- name: "Install TeamViewer package"
  apt:
    name: teamviewer
    state: latest
